In [2]:
import numpy as np

In [3]:
l = [1,2,3,4,5]


array = np.array(l)

In [7]:
array[1:5]

array([2, 3, 4, 5])

In [8]:
array[2]

np.int64(3)

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.random.randint(0,10, size = (3,3))

array([[5, 8, 9],
       [1, 1, 3],
       [8, 2, 4]], dtype=int32)

In [14]:
array[2] = 20

In [16]:
array

array([ 1,  2, 20,  4,  5])

In [17]:
array.sort()

In [18]:
array

array([ 1,  2,  4,  5, 20])

In [19]:
np.random.rand(3,3)

array([[0.24976084, 0.7389083 , 0.12681645],
       [0.53901398, 0.77700801, 0.42593421],
       [0.24820516, 0.90727967, 0.30041357]])

In [20]:
l = [2,2,5,6,4,2,1,2,3,4,5]
array = np.array(l)

In [21]:
array

array([2, 2, 5, 6, 4, 2, 1, 2, 3, 4, 5])

In [22]:
array.mean()

np.float64(3.272727272727273)

In [23]:
array.average()

AttributeError: 'numpy.ndarray' object has no attribute 'average'

In [24]:
array.std()

np.float64(1.5427784316797402)

In [25]:
array.var()

np.float64(2.3801652892561984)

In [27]:
array = np.arange(100)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [28]:
array = np.linspace(100,200, num = 10)
array

array([100.        , 111.11111111, 122.22222222, 133.33333333,
       144.44444444, 155.55555556, 166.66666667, 177.77777778,
       188.88888889, 200.        ])

In [29]:
np.full((2,3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [30]:
array = np.eye(3)

In [31]:
array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
array.shape

(3, 3)

In [33]:
array.size

9

In [34]:
array.dtype

dtype('float64')

In [35]:
array.astype(np.float32)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [36]:
array.tolist()

[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]

In [37]:
len(array)

3

In [38]:
np.sort(array  )

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [39]:
np.sort(array, axis = 0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.]])

In [42]:
array = np.append(array, [1,2,3])

In [43]:
array

array([1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 2., 3.])

In [46]:
array   = np.arange(5,11).reshape((3,2))

In [47]:
np.delete(array, 0) 

array([ 6,  7,  8,  9, 10])

In [49]:
array = array.reshape(2,3)

In [50]:
array

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [53]:
array = np.delete(array, 0)

In [54]:
array

array([ 6,  7,  8,  9, 10])

In [58]:
array = np.append(array, 1)

In [59]:
array = np.append(array, 2)

In [60]:
array.sort()

In [61]:
array 

array([ 1,  2,  6,  7,  8,  9, 10])

In [66]:
array  = np.delete(array,0)

In [67]:
array = array.reshape(2,3)

In [68]:
array

array([[ 2,  6,  7],
       [ 8,  9, 10]])

In [69]:
array.flatten()

array([ 2,  6,  7,  8,  9, 10])

In [72]:
array1 = array.transpose(1,0)

In [71]:
array2 = array.transpose(1,0)

In [73]:
array3 = np.concatenate((array1, array2), axis=0)

In [74]:
array3

array([[ 2,  8],
       [ 6,  9],
       [ 7, 10],
       [ 2,  8],
       [ 6,  9],
       [ 7, 10]])

In [75]:
array[array>2]

array([ 6,  7,  8,  9, 10])

In [76]:
array

array([[ 2,  6,  7],
       [ 8,  9, 10]])

In [79]:
array[1, 2]

np.int64(10)

In [80]:
np.median(array)

np.float64(7.5)

In [81]:
np.mode(array)

AttributeError: module 'numpy' has no attribute 'mode'

In [82]:
np.mean(array)

np.float64(7.0)

In [83]:
np.std(array)

np.float64(2.581988897471611)

In [84]:
np.max(array)

np.int64(10)

In [85]:
np.min(array)

np.int64(2)